---
# virt-nets/tasks/main.yml

- name: Install libvirt/lxml python module
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-libvirt
    - python-lxml

- name: collect libvirt network facts
  virt_net:
    command: facts

- name: Tear down libvirt's default network
  when: ansible_libvirt_networks["default"] is defined
  virt_net:
    command: "{{ item }}"
    name: "default"
  with_items:
    - destroy
    - undefine

# note, this isn't idempotent, so may need manual fixing if it changes
- name: Define libvirt networks settings (IP/DHCP/DNS)
  when: "{{ ansible_libvirt_networks[item.name] is not defined }}"
  virt_net:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'virt_net.xml.j2') }}"
  with_items: "{{ virt_nets }}"

- name: Collect libvirt network facts after defining new network
  virt_net:
    command: facts

- name: Start libvirt networks
  when: "{{ ansible_libvirt_networks[item.name].state != 'active' }}"
  virt_net:
    name: "{{ item.name }}"
    command: create
    autostart: yes
  with_items: "{{ virt_nets }}"

- name: Have libvirt networks automatically start on reboot
  when: "{{ ansible_libvirt_networks[item.name].autostart != 'yes' }}"
  virt_net:
    name: "{{ item.name }}"
    autostart: yes
  with_items: "{{ virt_nets }}"

