# Deployment configuration for a single-node POD on CloudLab
---
debug: false

seedServer:
  ip: '128.104.222.192'

  # User name used by Ansible to connect to the host for remote
  # provisioning.  Assumes private key loaded into ssh-agent.
  user: 'acb'

  extraVars:
    - 'on_cloudlab=True'

docker:
  imageVersion: candidate

