- name: Apt Repo
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: yes
  register: result
  until: result | success
  retries: 3
  delay: 10

- name: Apt packages
  apt:
    name: "{{ item }}"
  with_items: "{{ apt_packages }}"
  tags: [buildtools]

- name: Ensure Repo
  copy:
    src: repo.bin
    dest: /usr/local/bin/repo
    owner: root
    group: root
    mode: 0755

