- name: Apt Repo
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: yes

- name: Upgrade Packages
  apt:
    upgrade: yes

- name: Apt packages
  apt:
    name: "{{ item }}"
  with_items: "{{ apt_packages }}"
  tags: [buildtools]

