- name: Bridge Support is Present
  apt:
    name: bridge-utils
    force: yes
  tags: [prod]

- name: Ensure Management Bridge
  copy:
    src: mgmtbr.cfg
    dest: /etc/network/interfaces.d/mgmtbr.cfg
    owner: root
    group: root
    mode: 0644

- name: Ensure Management Bridge Up
  command: ifup mgmtbr
  changed_when: true

- name: Ensure fabric bridge
  copy:
    src: fabric.cfg
    dest: /etc/network/interfaces.d/fabric.cfg
    owner: root
    group: root
    mode: 0644

- name: Ensure fabric bridge
  command: ifup {{ item }}
  changed_when: true
  with_items:
  - fabric
  - fabric:0
  - fabric:1
